#!/usr/bin/env python3
"""
test_trt_backend.py -- Minimal TensorRT inference test, no ROS needed.

Usage:
    python3 test_trt_backend.py --engine model.engine --input input_debug.npy

input_debug.npy is generated by the previous test_model.py script.
If you don't have it, pass a JPG image with --image frame.jpg instead.
"""

import argparse
import ctypes
import ctypes.util
import sys

import numpy as np

IMAGENET_MEAN = np.array([0.485, 0.456, 0.406], dtype=np.float32)
IMAGENET_STD  = np.array([0.229, 0.224, 0.225], dtype=np.float32)


def load_input_from_npy(path: str) -> np.ndarray:
    arr = np.load(path)
    if arr.ndim == 4:
        arr = arr[0]   # remove batch dim -> (3, 256, 640)
    print(f"  Loaded npy: shape={arr.shape}  dtype={arr.dtype}"
          f"  range=[{arr.min():.3f}, {arr.max():.3f}]")
    return arr.astype(np.float32)


def load_input_from_image(path: str, crop_top: float = 0.45) -> np.ndarray:
    import cv2
    img = cv2.imread(path)
    if img is None:
        raise FileNotFoundError(f"Cannot read image: {path}")
    h       = img.shape[0]
    crop_px = int(h * crop_top)
    cropped = img[crop_px:, :]
    resized = cv2.resize(cropped, (640, 256), interpolation=cv2.INTER_LINEAR)
    rgb     = resized[:, :, ::-1].copy()   # BGR -> RGB
    norm    = (rgb.astype(np.float32) / 255.0 - IMAGENET_MEAN) / IMAGENET_STD
    chw     = norm.transpose(2, 0, 1)      # HWC -> CHW (3, 256, 640)
    print(f"  Loaded image: shape={chw.shape}  dtype={chw.dtype}"
          f"  range=[{chw.min():.3f}, {chw.max():.3f}]")
    return chw


def run_test(engine_path: str, inp: np.ndarray):
    try:
        import tensorrt as trt
    except ImportError:
        print("ERROR: tensorrt not found.")
        print("  export PYTHONPATH=/usr/lib/python3.6/dist-packages:$PYTHONPATH")
        sys.exit(1)

    # Load cudart
    rt = None
    for lib in ("libcudart.so.10.2", "libcudart.so",
                "/usr/local/cuda/lib64/libcudart.so"):
        try:
            rt = ctypes.CDLL(lib)
            print(f"  cudart loaded: {lib}")
            break
        except OSError:
            continue
    if rt is None:
        print("ERROR: cannot load libcudart.so")
        sys.exit(1)

    def cu(result, label=""):
        if result != 0:
            raise RuntimeError(f"CUDA error {result} in {label}")

    # Load engine
    print(f"\n  Loading engine: {engine_path}")
    TRT_LOGGER = trt.Logger(trt.Logger.WARNING)
    with open(engine_path, "rb") as f:
        engine = trt.Runtime(TRT_LOGGER).deserialize_cuda_engine(f.read())

    # Print binding info
    dtype_map = {
        trt.DataType.FLOAT: (np.float32, 4),
        trt.DataType.HALF:  (np.float16, 2),
        trt.DataType.INT32: (np.int32,   4),
        trt.DataType.INT8:  (np.int8,    1),
    }

    print("\n  Bindings:")
    binding_info = []
    for b in engine:
        shape      = tuple(max(s, 1) for s in engine.get_binding_shape(b))
        trt_dtype  = engine.get_binding_dtype(b)
        np_dtype, item_size = dtype_map.get(trt_dtype, (np.float32, 4))
        is_input   = engine.binding_is_input(b)
        print(f"    {b}: shape={shape}  trt_dtype={trt_dtype}"
              f"  np_dtype={np_dtype.__name__}  item_size={item_size}B"
              f"  {'INPUT' if is_input else 'OUTPUT'}")
        binding_info.append({
            "name":      b,
            "shape":     shape,
            "np_dtype":  np_dtype,
            "item_size": item_size,
            "is_input":  is_input,
        })

    context = engine.create_execution_context()

    # Allocate device buffers
    dev_bufs  = []
    host_arrs = []
    bindings  = []

    for info in binding_info:
        n      = int(np.prod(info["shape"]))
        nbytes = n * info["item_size"]
        d_ptr  = ctypes.c_void_p()
        cu(rt.cudaMalloc(ctypes.byref(d_ptr), nbytes), "cudaMalloc")
        dev_bufs.append(d_ptr)
        host_arrs.append(np.empty(n, dtype=info["np_dtype"]))
        bindings.append(d_ptr.value)

    # Find input/output indices
    in_idx  = [i for i, info in enumerate(binding_info) if info["is_input"]]
    out_idx = [i for i, info in enumerate(binding_info) if not info["is_input"]]

    # Copy input to GPU
    inp_flat = inp.astype(np.float32).ravel()
    n_in     = inp_flat.size
    cu(rt.cudaMemcpy(
        dev_bufs[in_idx[0]],
        inp_flat.ctypes.data_as(ctypes.c_void_p),
        n_in * 4,
        ctypes.c_int(1)), "cudaMemcpy H2D")   # H2D = 1

    # Run inference (synchronous, no stream)
    print("\n  Running execute_v2...")
    ok = context.execute_v2(bindings=bindings)
    print(f"  execute_v2 returned: {ok}")

    # Copy each output from GPU and analyse
    print("\n  Outputs:")
    for i in out_idx:
        info   = binding_info[i]
        n_out  = int(np.prod(info["shape"]))
        nbytes = n_out * info["item_size"]
        out    = np.empty(n_out, dtype=info["np_dtype"])

        cu(rt.cudaMemcpy(
            out.ctypes.data_as(ctypes.c_void_p),
            dev_bufs[i],
            nbytes,
            ctypes.c_int(2)), "cudaMemcpy D2H")   # D2H = 2

        out_shaped = out.reshape(info["shape"])
        print(f"\n    Binding '{info['name']}':")
        print(f"      shape    : {out_shaped.shape}")
        print(f"      dtype    : {out_shaped.dtype}")
        print(f"      range    : [{out.min()}, {out.max()}]")

        # If output is float (logits), apply argmax to get classes
        if info["np_dtype"] in (np.float32, np.float16):
            print(f"      raw range: [{float(out.min()):.4f}, {float(out.max()):.4f}]")
            print("      Output is FLOAT -- engine outputs logits, not class indices.")
            print("      Applying argmax to get class predictions...")
            # Output shape is (1, num_classes, H, W) or (1, H, W)
            if out_shaped.ndim == 4:
                # (1, C, H, W) -> argmax over C
                classes = out_shaped[0].argmax(axis=0)
            elif out_shaped.ndim == 3:
                # (1, H, W) -- already class indices stored as float
                classes = out_shaped[0].astype(np.int32)
            else:
                classes = out_shaped.astype(np.int32)
        else:
            # INT32/INT8 -- already class indices
            classes = out_shaped[0] if out_shaped.ndim == 3 else out_shaped
            classes = classes.astype(np.int32)

        unique, counts = np.unique(classes, return_counts=True)
        print(f"      unique classes: {unique.tolist()}")
        print(f"      class counts  : {dict(zip(unique.tolist(), counts.tolist()))}")
        total = classes.size
        for cls, cnt in zip(unique.tolist(), counts.tolist()):
            print(f"        class {cls}: {cnt} px  ({100*cnt/total:.1f}%)")

    # Free device memory
    for d in dev_bufs:
        rt.cudaFree(d)

    print("\n  Done.")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--engine", required=True, help="Path to .engine file")
    parser.add_argument("--input",  default=None,
                        help="Path to input_debug.npy (from test_model.py)")
    parser.add_argument("--image",  default=None,
                        help="Path to a JPG/PNG frame (alternative to --input)")
    parser.add_argument("--crop-top", type=float, default=0.45, dest="crop_top")
    args = parser.parse_args()

    if args.input:
        inp = load_input_from_npy(args.input)
    elif args.image:
        inp = load_input_from_image(args.image, args.crop_top)
    else:
        print("ERROR: provide --input <npy> or --image <jpg>")
        sys.exit(1)

    run_test(args.engine, inp)


if __name__ == "__main__":
    main()